-- NOT generated by ./regenPublicObjects.sh, so we can also export String.

-- A variant of Objects which only export the type constructors, not the data constructors,
-- so the player cannot cheat.
module PublicObjects (PaperDispenser, Paper, Pen, String) where

import Objects
