name: hyzzy
version: 0.1
synopsis: Text adventures where actions have types
description: A framework for defining text adventures via Haskell files. Play by combining functions, not by guessing phrases.
homepage:            https://github.com/gelisam/hyzzy#readme
github:              gelisam/hyzzy
license:             PublicDomain
author:              Samuel Gélineau
maintainer:          gelisam+github@gmail.com
category:            Game
extra-source-files:
  - README.md
ghc-options: -W -Wall

library:
  source-dirs: lib
  dependencies:
    - base

executables:
  hyzzy:
    source-dirs: exe
    main: Main
    dependencies:
      - base
      - containers
      - exceptions
      - generic-lens
      - haskeline
      - hint
      - hyzzy
      - lens
      - mmorph
      - transformers
