#!/bin/bash

function usage {
  echo "usage:"
  echo "  $0 [games/<game-name>]"
  echo
  echo "Generate \"games/<game-name>/PublicObjects.hs\""
  echo "based on \"games/<game-name>/Objects.hs\"."
}

function generatePublicObjects {
  echo "-- GENERATED BY \"$0 $ARGS\", DO NOT MODIFY BY HAND"
  echo
  echo "-- A variant of Objects which only export the type constructors, not the data constructors,"
  echo "-- so the player cannot cheat."
  echo -n "module PublicObjects ("
  sed 's/$/, /g' | tr '\n' '' | sed 's/, $/) where/g' | tr -d ''
  echo
  echo "import Objects"
}

ARGS="$@"
if [ "$1" = "--help" -o "$1" = "-h" ]; then
  usage
elif [ -d "$1" -a -f "$1/Objects.hs" ]; then
  # e.g. "games/castle"
  GAME="$1"

  cat "$GAME/Objects.hs" | \
    grep '^newtype' | \
    cut -d' ' -f2 | \
    generatePublicObjects > "$GAME/PublicObjects.hs"
else
  usage
  exit 1
fi
