#!/bin/bash

function generatePublicObjects {
  echo "-- GENERATED BY $0, DO NOT MODIFY BY HAND"
  echo
  echo "-- A variant of Objects which only export the type constructors, not the data constructors,"
  echo "-- so the player cannot cheat."
  echo -n "module PublicObjects ("
  sed 's/$/, /g' | tr '\n' '' | sed 's/, $/) where/g' | tr -d ''
  echo
  echo "import Objects"
}

cat "games/castle/Objects.hs" | \
  grep '^newtype' | \
  cut -d' ' -f2 | \
  generatePublicObjects > "games/castle/PublicObjects.hs" 
