-- GENERATED BY ./regenPublicObjects.sh, DO NOT MODIFY BY HAND

-- A variant of Objects which only export the type constructors, not the data constructors,
-- so the player cannot cheat.
module PublicObjects (Key, Door) where

import Objects
